name: Mypy Check

on:
  push:
    branches:
      - main  # Замените на вашу основную ветку
  pull_request:
    branches:
      - main  # Замените на вашу основную ветку

jobs:
  mypy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy

      - name: Run mypy
        run: |
          cd src/app && mypy . --strict
