name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.9'  # Замените на вашу версию Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/app/requirements.txt

      - name: Run tests with coverage
        run: |
          pip install pytest pytest-cov
          pytest --cov=src/app --cov-report=xml --cov-report=term-missing tests/unit  # Запуск тестов с покрытием

      - name: Upload coverage report
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage.xml
